MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Models;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentLoggedInUser _currentLoggedInUser;
        private readonly IUserService _userService;

        public UserController(ICurrentLoggedInUser currentLoggedInUser, IUserService userService)
        {
            _currentLoggedInUser = currentLoggedInUser;
            _userService = userService;
        }

        //Purchases, that will give list of movies user purchased and should return a View that will show MovieCards and should use MovieCard partial view.
        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            //var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];

            var userId = _currentLoggedInUser.UserId;

            //get all movies purchased by current user
            var movies = await _userService.GetAllPurchasesForUserId(userId);

            return View(movies);
        }

        //Favorites, that will give list of movies user Favorited and should return a View that will show MovieCards and should use MovieCard partial view.
        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            var userId = _currentLoggedInUser.UserId;

            var movies = await _userService.GetAllFavoritesForUser(userId);

            return View(movies);
        }

        [HttpPost]
        public async Task<IActionResult> ReviewAction(ReviewRequestModel model, string submitButton)
        {
            switch (submitButton)
            {
                case "Submit":
                    return await AddReview(model);
                case "Delete":
                    return await DeleteReview(model);
            }

            return LocalRedirect("~/");
        }

        //Review for user to add a new Review, when user clicks on Review button in Movie Details Page and Review Confirmation Popup
        //[HttpPost]
        public async Task<IActionResult> AddReview(ReviewRequestModel model)
        {
            
            //get review for user and movie
            var userId = _currentLoggedInUser.UserId;
            var review = await _userService.GetReview(userId, model.MovieId);

            //if review doesn't exists, add review
            if(review.UserId == 0)
            {
                var res = await _userService.AddMovieReview(model);
            }
            else
            {
                //else, update review
                var res = await _userService.UpdateMovieReview(model);
            }
            

            return RedirectToAction("Details", "Movies", new { id = model.MovieId });
        }

        //[HttpPost]
        public async Task<IActionResult> DeleteReview(ReviewRequestModel model)
        {
            
            //get review for user and movie
            var userId = _currentLoggedInUser.UserId;
            var review = await _userService.GetReview(userId, model.MovieId);

            //if review exists, delete review
            if(review.UserId > 0)
            {
                var res = await _userService.DeleteMovieReview(userId, model.MovieId);
            }
            

            return RedirectToAction("Details", "Movies", new { id = model.MovieId });
        }

        [HttpPost]
        public async Task<IActionResult> AddFavorite(int movieId)
        {
            //check if already favorited
            var userId = _currentLoggedInUser.UserId;
            var favorited = await _userService.FavoriteExists(userId, movieId);

            var model = new FavoriteRequestModel
            {
                MovieId = movieId,
                UserId = userId
            };

            //update favorite based on current favorited status
            if (favorited)
            {

                var fav = await _userService.GetFavoriteById(userId, movieId);
                model.Id = fav.Id;
                var res = await _userService.RemoveFavorite(model);
            }
            else
            {
                var res = await _userService.AddFavorite(model);
            }

            
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        //Buy for user to buy a movie, when user click on Purchase button in Movie Details Page Purchase Confirmation Popup
        [HttpPost]
        public async Task<IActionResult> BuyMovie(int movieId)
        {
            //check if movie already purchased
            var userId = _currentLoggedInUser.UserId;
            var purchased = await _userService.IsMoviePurchased(userId, movieId);

            //add to purchase db/user
            if (!purchased)
            {
                var purchaseRequest = new PurchaseRequestModel
                {
                    MovieId = movieId,
                    PurchaseDate = DateTime.Now,                 
                };

                var purchase = await _userService.PurchaseMovie(purchaseRequest, userId);
            }
         
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            return View();
        }
    }
}

MovieShopMVC/Views/Shared/Components/Favorite/FavoriteViewComponent.cs
using ApplicationCore.Models;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Views.Shared.Components.Favorite
{
    public class FavoriteViewComponent : ViewComponent
    {
        private readonly ICurrentLoggedInUser _currentLoggedInUser;
        private readonly IUserService _userService;


        public FavoriteViewComponent(ICurrentLoggedInUser currentLoggedInUser, IUserService userService)
        {
            _currentLoggedInUser = currentLoggedInUser;
            _userService = userService;
        }


        public async Task<IViewComponentResult> InvokeAsync(int movieId)
        {

            var model = new FavoriteModel { 
                MovieId = movieId,
                Toggle = this.HttpContext.User.Identity.IsAuthenticated,
                IsFavorite = this.HttpContext.User.Identity.IsAuthenticated ? await _userService.FavoriteExists(_currentLoggedInUser.UserId, movieId) : false
            };

            return View(model);
        }
    }
}

MovieShopMVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using ApplicationCore.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }
    }
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu">
                                @await Component.InvokeAsync("Genres")
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginInfo" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_LoginInfo.cshtml
@using MovieShopMVC.Services


@inject ICurrentLoggedInUser currentUser

@if(currentUser.IsAuthenticated)
{
    <div class="text-end">
        <ul class="nav">
            <li class="nav-item dropdown text-capitalize">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownProfile" data-bs-toggle="dropdown">
                    @currentUser.FullName
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="User" asp-action="Purchases">Purchases</a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Favorites">Favorites</a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Profile">Profile</a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
                </div>
            </li>
        </ul>
    </div>
}
else
{
    <div class="text-end">
        <a class="btn btn-outline-primary me-2" asp-controller="Account" asp-action="Login">Login</a>
        <a class="btn btn-outline-primary me-2" asp-controller="Account" asp-action="Register">Register</a>
    </div>
}

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardModel


<div class="card mb-4 shadow">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title">
    </a>
</div>

MovieShopMVC/Views/Shared/_MoviePurchaseCard.cshtml
@model ApplicationCore.Models.PurchaseRequestModel


<div class="card mb-0 shadow">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.MovieId">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title">
    </a>
</div>

MovieShopMVC/Views/Shared/_ReviewModal.cshtml
@model ApplicationCore.Models.ReviewRequestModel


<div class="modal fade"
     id="reviewModal"
     tabindex="-1"
     aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    What did you think?
                </h5>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <form asp-controller="User" asp-action="ReviewAction">              
                <input type="hidden" asp-for="MovieId" value="@Model.MovieId" /> 
                <input type="hidden" asp-for="UserId" value="@Model.UserId" />
                <div class="modal-body d-flex">
                    <select class="form-select me-2 w-25" asp-for="Rating">
                        @for (int i = 1; i <= 10; i++)
                        {
                            if(i == Model.Rating)
                            {
                                <option selected value="@i">@i</option>
                            }
                            else
                            {
                                <option value="@i">@i</option>
                            }                                                    
                        }
                    </select>
                    <div class="input-group">
                        <textarea class="form-control" asp-for="ReviewText"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" name="submitButton" value="Delete" />
                    <input type="submit" class="btn btn-primary" name="submitButton" value="Submit" />
                </div>
            </form>
        </div>
    </div>
</div>