MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
           var cast = await _castService.GetCastDetails(id);

            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Models;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ICurrentLoggedInUser _currentLoggedInUser;
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public MoviesController(IMovieService movieService, ICurrentLoggedInUser currentLoggedInUser, IUserService userService)
        {
            _movieService = movieService;
            _currentLoggedInUser = currentLoggedInUser;
            _userService = userService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = - 1;
            var reviewModel = new ReviewRequestModel { Rating = 0, ReviewText = "" };

            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                userId = _currentLoggedInUser.UserId;
                reviewModel = await _userService.GetReview(userId, id);

                if(reviewModel.UserId == 0)
                {
                    reviewModel.UserId = userId;
                    reviewModel.MovieId = id;
                }
                    
            }

            var movie = await _movieService.GetMovieDetails(id, userId);
            movie.Review = reviewModel;
            

            return View(movie);
        }

        public async Task<IActionResult> Genres(int id, int pageSize = 30, int pageNumber = 1)
        {
            var movies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);

            return View("PagedMovies", movies);
        }
    }
}

MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Models;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentLoggedInUser _currentLoggedInUser;
        private readonly IUserService _userService;

        public UserController(ICurrentLoggedInUser currentLoggedInUser, IUserService userService)
        {
            _currentLoggedInUser = currentLoggedInUser;
            _userService = userService;
        }

        //Purchases, that will give list of movies user purchased and should return a View that will show MovieCards and should use MovieCard partial view.
        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            //var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];

            var userId = _currentLoggedInUser.UserId;

            //get all movies purchased by current user
            var movies = await _userService.GetAllPurchasesForUserId(userId);

            return View(movies);
        }

        //Favorites, that will give list of movies user Favorited and should return a View that will show MovieCards and should use MovieCard partial view.
        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            var userId = _currentLoggedInUser.UserId;

            var movies = await _userService.GetAllFavoritesForUser(userId);

            return View(movies);
        }

        [HttpPost]
        public async Task<IActionResult> ReviewAction(ReviewRequestModel model, string submitButton)
        {
            switch (submitButton)
            {
                case "Submit":
                    return await AddReview(model);
                case "Delete":
                    return await DeleteReview(model);
            }

            return LocalRedirect("~/");
        }

        //Review for user to add a new Review, when user clicks on Review button in Movie Details Page and Review Confirmation Popup
        //[HttpPost]
        public async Task<IActionResult> AddReview(ReviewRequestModel model)
        {
            
            //get review for user and movie
            var userId = _currentLoggedInUser.UserId;
            var review = await _userService.GetReview(userId, model.MovieId);

            //if review doesn't exists, add review
            if(review.UserId == 0)
            {
                var res = await _userService.AddMovieReview(model);
            }
            else
            {
                //else, update review
                var res = await _userService.UpdateMovieReview(model);
            }
            

            return RedirectToAction("Details", "Movies", new { id = model.MovieId });
        }

        //[HttpPost]
        public async Task<IActionResult> DeleteReview(ReviewRequestModel model)
        {
            
            //get review for user and movie
            var userId = _currentLoggedInUser.UserId;
            var review = await _userService.GetReview(userId, model.MovieId);

            //if review exists, delete review
            if(review.UserId > 0)
            {
                var res = await _userService.DeleteMovieReview(userId, model.MovieId);
            }
            

            return RedirectToAction("Details", "Movies", new { id = model.MovieId });
        }

        [HttpPost]
        public async Task<IActionResult> AddFavorite(int movieId)
        {
            //check if already favorited
            var userId = _currentLoggedInUser.UserId;
            var favorited = await _userService.FavoriteExists(userId, movieId);

            var model = new FavoriteRequestModel
            {
                MovieId = movieId,
                UserId = userId
            };

            //update favorite based on current favorited status
            if (favorited)
            {

                var fav = await _userService.GetFavoriteById(userId, movieId);
                model.Id = fav.Id;
                var res = await _userService.RemoveFavorite(model);
            }
            else
            {
                var res = await _userService.AddFavorite(model);
            }

            
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        //Buy for user to buy a movie, when user click on Purchase button in Movie Details Page Purchase Confirmation Popup
        [HttpPost]
        public async Task<IActionResult> BuyMovie(int movieId)
        {
            //check if movie already purchased
            var userId = _currentLoggedInUser.UserId;
            var purchased = await _userService.IsMoviePurchased(userId, movieId);

            //add to purchase db/user
            if (!purchased)
            {
                var purchaseRequest = new PurchaseRequestModel
                {
                    MovieId = movieId,
                    PurchaseDate = DateTime.Now,                 
                };

                var purchase = await _userService.PurchaseMovie(purchaseRequest, userId);
            }
         
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            return View();
        }
    }
}

MovieShopMVC/Views/Shared/Components/Favorite/FavoriteViewComponent.cs
using ApplicationCore.Models;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Views.Shared.Components.Favorite
{
    public class FavoriteViewComponent : ViewComponent
    {
        private readonly ICurrentLoggedInUser _currentLoggedInUser;
        private readonly IUserService _userService;


        public FavoriteViewComponent(ICurrentLoggedInUser currentLoggedInUser, IUserService userService)
        {
            _currentLoggedInUser = currentLoggedInUser;
            _userService = userService;
        }


        public async Task<IViewComponentResult> InvokeAsync(int movieId)
        {

            var model = new FavoriteModel { 
                MovieId = movieId,
                Toggle = this.HttpContext.User.Identity.IsAuthenticated,
                IsFavorite = this.HttpContext.User.Identity.IsAuthenticated ? await _userService.FavoriteExists(_currentLoggedInUser.UserId, movieId) : false
            };

            return View(model);
        }
    }
}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel


<style>
    .movie-facts .list-group-item {
        border-color: black;
    }

    .movie-facts {
        background-color: rgb(236, 236, 236);
    }

    .cast-img {
        width: 65%;
    }
</style>
<div class="container-fluid pt-1 mb-2 h-100">
    <!--top-->
    <div class="container-fluid"
         style="
          background: url(@Model.BackdropUrl) no-repeat fixed center;
          background-size: cover;
            background-color: rgba(0, 0, 0, 0.5);
            background-blend-mode: color;
        ">
        <div class="row gx-5">
            <!--poster-->
            <div class="col-lg-4">
                <img class="w-50 h-100 float-lg-end mx-5"
                     src=@Model.PosterUrl
                     alt="" />
            </div>
            <!--details-->
            <div class="col-lg-6">
                <div class="container">
                    <h1 class="text-light">@Model.Title</h1>
                    <h6 class="text-secondary">@Model.Tagline</h6>
                    <div class="row mb-2">
                        <div class="col-4">
                            <h4 class="text-secondary">@Model.RunTime m | @Model.ReleaseYear</h4>
                        </div>
                        <div class="col-8">
                            @foreach (var genre in @Model.Genres)
                            {
                                <span class="badge rounded-pill bg-secondary">@genre.Name</span>
                            }
                        </div>
                    </div>
                    <div class="mb-3">
                        <span class="badge" style="background-color: rgb(1, 185, 1)">@Model.Rating</span>
                    </div>
                    <p class="text-light fw-lighter">
                        @Model.Overview
                    </p>
                </div>
            </div>
            <!--btns-->
            <div class="col-lg-2">
                <div class="container d-flex flex-column mt-5 ps-0 pe-0 h-100">
                    <button class="btn btn-outline-light mb-4" data-bs-toggle="modal" data-bs-target="#reviewModal">
                        <i class="fa-regular fa-pen-to-square me-2"></i>REVIEW
                    </button>
                    @if (Model.IsPurchased)
                    {
                        <button class="btn btn-light mb-4">
                            Watch Movie
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-light mb-4 " data-bs-toggle="modal" data-bs-target="#purchaseModal">
                            BUY $@Model.Price
                        </button>
                    }

                    @await Component.InvokeAsync("Favorite", new {movieId = @Model.Id})

                    <!-- Modals -->
                    <!-- Review -->
                    <partial name="_ReviewModal" model="@Model.Review">

                    <!-- Purchase -->
                    <div class="modal fade"
                         id="purchaseModal"
                         tabindex="-1"
                         aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">
                                        Confirm Purchase
                                    </h5>
                                    <button type="button"
                                            class="btn-close"
                                            data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Confirming purchase of @Model.Title for $@Model.Price ?
                                </div>
                                <form asp-action="BuyMovie" asp-controller="User" asp-route-movieId="@Model.Id">
                                    <div class="modal-footer">
                                        <button type="button"
                                                class="btn btn-secondary"
                                                data-bs-dismiss="modal">
                                            Close
                                        </button>
                                        <button class="btn btn-primary" type="submit">
                                            Confirm
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--bottom-->
    <div class="container-fluid mt-3 mb-0">
        <div class="row">
            <!--movie facts-->
            <div class="col-lg-4">
                <div class="container pb-3 mb-0 movie-facts h-100">
                    <h3 class="text-dark text-uppercase">movie facts</h3>
                    <hr class="mx-2" />
                    <ul class="movie-facts list-group list-group-flush mx-2">
                        <li class="movie-facts list-group-item">
                            <i class="fa-regular fa-calendar me-2"></i>Release Date
                            <span class="badge rounded-pill bg-dark">@Model.ReleaseDate</span>
                        </li>
                        <li class="movie-facts list-group-item">
                            <i class="fa-regular fa-hourglass me-2"></i>Run Time
                            <span class="badge rounded-pill bg-dark">@Model.RunTime</span>
                        </li>
                        <li class="movie-facts list-group-item">
                            <i class="fa-solid fa-money-bill me-2"></i>Box Office
                            <span class="badge rounded-pill bg-dark">@Model.Revenue</span>
                        </li>
                        <li class="movie-facts list-group-item">
                            <i class="fa-solid fa-dollar-sign me-2"></i>Budget
                            <span class="badge rounded-pill bg-dark">@Model.Budget</span>
                        </li>
                        <li class="movie-facts list-group-item">
                            <i class="fa-solid fa-square-minus me-2"></i>
                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                        </li>
                    </ul>
                    <h3 class="text-dark text-uppercase mt-5">trailers</h3>
                    <hr class="mx-2" />
                    <ul class="movie-facts list-group list-group-flush mx-2">
                        @foreach (var trailer in @Model.Trailers)
                        {
                            <li class="movie-facts list-group-item">
                                <i class="fa-brands fa-youtube me-2"></i><a href="@trailer.TrailerUrl" class="text-decoration-none text-dark">@trailer.Name</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <!--cast-->
            <div class="col-lg-7">
                <div class="container ms-5 pe-5">
                    <ul class="cast-list list-group list-group-flush pe-5">
                        <li class="list-group-item">
                            <h3 class="text-dark text-uppercase">cast</h3>
                        </li>
                        @foreach (var cast in @Model.Casts)
                        {
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-2">
                                        <a asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id">
                                            <img src=@cast.ProfilePath
                                             alt="@cast.Name"
                                             class="rounded-circle cast-img" />
                                        </a>
                                    </div>
                                    <div class="col-4 ms-3 mt-2">@cast.Name</div>
                                    <div class="col-4 ms-3 mt-2">@cast.Character</div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

MovieShopMVC/Views/Movies/PagedMovies.cshtml
@model ApplicationCore.Models.PagedResultSetModel<ApplicationCore.Models.MovieCardModel>

<div class="rounded">
    <div class="container bg-light">
        <div class="row">
            @foreach (var movie in Model.PagedData)
            {
                <div class="col-xl-2 col-lg-3 col-sm-4 col-6">
                    <partial name="_MovieCard" model="movie">
                </div>
            }
        </div>
    </div>
</div>

@{
    var previousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item @previousDisabled">
      <a class="page-link" asp-action="Genres" asp-controller="Movies" asp-route-pageNumber="1" aria-label="First">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="page-item @previousDisabled">
      <a class="page-link" asp-action="Genres" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber - 1)" aria-label="Previous">
        <span aria-hidden="true">&lt;</span>
      </a>
    </li>
        @for(int i = @Model.PaginationStart; i <= @Model.PaginationStart + @Model.PaginationRange; i++)
        {
            
            var active = i == @Model.PageNumber ? "active" : "";
            
            <li class="page-item @active"><a class="page-link" asp-action="Genres" asp-controller="Movies" asp-route-pageNumber="@i">@i</a></li>
        }
    @*<li class="page-item">
      <a class="page-link" href="#" aria-label="select">
        <span aria-hidden="true">&hellip;</span>
      </a>
    </li>*@
    <li class="page-item @nextDisabled">
      <a class="page-link" asp-action="Genres" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber + 1)" aria-label="Next">
        <span aria-hidden="true">&gt;</span>
      </a>
    </li>
    <li class="page-item @nextDisabled">
      <a class="page-link" asp-action="Genres" asp-controller="Movies" asp-route-pageNumber="@(Model.TotalPages)" aria-label="Last">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>